name: pushEvent
on: push
jobs:
  add_text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |   
          echo "Hello GitHub Actions!" >> hello.txt
          git config user.name github-actions
          git config user.email katanaka@sra.co.jp
          git add .
          git commit -m "generated"
          git push
